// CI / git-hooks installer: GitHub Actions workflow generation, the
// init-hook pre-commit installer (husky/native/github-action), and the
// ci install|config|upgrade subcommands that read-modify-write an
// already-installed workflow. Split out of the former monolithic
// scripts/detect.mjs — no behavior change.

import { promises as fs } from "node:fs";
import * as fsSync from "node:fs";
import path from "node:path";
import readline from "node:readline";

import { VERSION, red, yellow, dim, bold, c, SCOPE_VALUES, FAIL_ON_VALUES } from "./constants.mjs";

// --- init-hook subcommand -------------------------------------------------

const HOOK_NATIVE_PATH = ".githooks/pre-commit";
const HOOK_HUSKY_PATH = ".husky/pre-commit";
const HOOK_GHA_PATH = ".github/workflows/ui-craft-detect.yml";

const NATIVE_HOOK_CONTENT = `#!/usr/bin/env bash
# ui-craft-detect pre-commit hook (native, no deps).
# Generated by \`ui-craft-detect init-hook --native\`.

set -e

STAGED=$(git diff --cached --name-only --diff-filter=ACM \\
  | grep -E '\\.(css|scss|sass|tsx|jsx|ts|js|vue|svelte|astro|html)$' || true)

if [ -z "$STAGED" ]; then
  exit 0
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

while IFS= read -r file; do
  mkdir -p "$TMPDIR/$(dirname "$file")"
  git show ":$file" > "$TMPDIR/$file" 2>/dev/null || true
done <<< "$STAGED"

cd "$TMPDIR"
if npx ui-craft-detect . ; then
  exit 0
else
  echo ""
  echo "ui-craft-detect found issues in staged files."
  echo "Fix them, re-stage, and commit \u2014 or use 'git commit --no-verify'."
  exit 1
fi
`;

const HUSKY_HOOK_CONTENT = `#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx ui-craft-detect .
`;

const GHA_CONFIG_MARKER = "# ui-craft-detect-config:";
const GHA_VERSION_MARKER = "# ui-craft-detect-version:";
const GHA_STICKY_COMMENT_MARKER = "<!-- ui-craft-detect -->";

/**
 * Default config embedded in a freshly-generated workflow. `ci config`/`ci
 * upgrade` (Slice D) read-modify-write this via the marker comments below;
 * these values ALWAYS win over template defaults on regen.
 * @typedef {{scope: "full"|"files"|"changed", failOn: "none"|"warning"|"error", comment: boolean, inlineComments: boolean, status: boolean}} GhaConfig
 */
export const DEFAULT_GHA_CONFIG = Object.freeze({
  scope: "changed",
  failOn: "error",
  comment: true,
  inlineComments: true,
  status: true,
});

/**
 * Renders the generated GitHub Actions workflow YAML as a plain string.
 *
 * Scan-invocation policy (decided in Slice B, load-bearing for Slice C):
 * - `pull_request` runs use `config.scope`/`config.failOn` as-is — a PR
 *   diff/base ref is guaranteed, so "changed" scope is meaningful.
 * - `push` runs (default-branch pushes) ALWAYS use `--scope full`,
 *   regardless of `config.scope`. A push has no PR diff context, so
 *   "changed" scope cannot be resolved reliably (squash/merge commits,
 *   force-pushes, etc. make a single-parent diff fragile). `--fail-on`
 *   still follows `config.failOn`. Slice C's commit-status step reuses
 *   this same push-triggered job and its full-scope scan result.
 *
 * @param {GhaConfig} config
 * @returns {string}
 */
export function renderGHAWorkflow(config) {
  const resolved = { ...DEFAULT_GHA_CONFIG, ...config };
  const { scope, failOn, comment, status, inlineComments } = resolved;

  const stickyCommentStep = comment
    ? `
      - name: Post or update sticky PR summary comment
        if: always() && github.event_name == 'pull_request'
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -e
          REPO="\${{ github.repository }}"
          PR_NUMBER="\${{ github.event.number }}"
          MARKER='${GHA_STICKY_COMMENT_MARKER}'
          BODY_FILE="$(mktemp)"
          printf '%s\\n\\n' "$MARKER" > "$BODY_FILE"
          MD_FILE="$(mktemp)"
          npx --yes ui-craft-detect@latest . --scope changed --fail-on none --markdown > "$MD_FILE" || true
          cat "$MD_FILE" >> "$BODY_FILE"
          cat "$MD_FILE" >> "$GITHUB_STEP_SUMMARY"
          COMMENT_ID="$(gh api "repos/$REPO/issues/$PR_NUMBER/comments" --paginate --jq \\
            ".[] | select(.body | contains(\\"$MARKER\\")) | .id" | head -n1)"
          if [ -n "$COMMENT_ID" ]; then
            gh api --method PATCH "repos/$REPO/issues/comments/$COMMENT_ID" -F body=@"$BODY_FILE"
          else
            gh api --method POST "repos/$REPO/issues/$PR_NUMBER/comments" -F body=@"$BODY_FILE"
          fi`
    : "";

  // Slice C1: commit-status step. Reuses the push-triggered scan step's JSON
  // output (captured to a temp file in that same step) — no third scan
  // invocation. Gated on config.status and non-pull_request events (a push
  // has no PR to attach an inline/sticky comment to; the commit status is
  // the push-side signal). `continue-on-error: true` — the separate
  // failOnExit-derived scan step remains the sole authoritative gate.
  const commitStatusStep = status
    ? `
      - name: Publish commit status
        if: always() && github.event_name != 'pull_request'
        continue-on-error: true
        env:
          GH_TOKEN: \${{ github.token }}
          SCAN_JSON_FILE: \${{ runner.temp }}/ui-craft-detect-scan.json
        run: |
          set -e
          ERRORS="$(jq -r '.summary.errors' "$SCAN_JSON_FILE")"
          WARNINGS="$(jq -r '.summary.warnings' "$SCAN_JSON_FILE")"
          if [ "$ERRORS" -gt 0 ]; then
            STATE="failure"
          else
            STATE="success"
          fi
          DESCRIPTION="$ERRORS errors, $WARNINGS warnings"
          gh api --method POST "repos/\${{ github.repository }}/statuses/\${{ github.sha }}" \\
            -f state="$STATE" \\
            -f context="ui-craft-detect" \\
            -f target_url="\${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }}" \\
            -f description="$DESCRIPTION"`
    : "";

  const permissionsStatusLine = status
    ? `
  # needed to publish the ui-craft-detect commit status
  statuses: write`
    : "";

  // Slice C2: inline review comments. Runs only on pull_request (a push has
  // no PR to attach a review to). Re-invokes the scan with --scope changed
  // --review-json — this recomputes hunks + re-scans rather than reusing the
  // pull_request scan step's plain --json output above, since --review-json
  // produces a different payload shape (GitHub Reviews API comments, not the
  // scan's own findings JSON) and needs its own commit_id. `continue-on-error:
  // true` — a 422 (force-push commit_id drift, renamed files) must never fail
  // the job; the earlier --fail-on-derived scan step remains the sole
  // authoritative gate. Gated on `always()` like the commit-status step: if
  // the pull_request scan step above exits non-zero (findings breach
  // --fail-on), GitHub Actions would otherwise skip this step by default —
  // but inline comments on a *failing* PR are exactly the case reviewers most
  // need to see, so this step must still run.
  const inlineCommentsStep = inlineComments
    ? `
      - name: Post inline review comments
        if: always() && github.event_name == 'pull_request'
        continue-on-error: true
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          REPO="\${{ github.repository }}"
          PR_NUMBER="\${{ github.event.number }}"
          HEAD_SHA="\${{ github.event.pull_request.head.sha }}"
          REVIEW_FILE="$(mktemp)"
          npx --yes ui-craft-detect@latest . --scope changed --fail-on none \\
            --review-json --commit-sha "$HEAD_SHA" > "$REVIEW_FILE" || true
          COMMENT_COUNT="$(jq -r 'if . == null then 0 else (.comments | length) end' "$REVIEW_FILE")"
          if [ "$COMMENT_COUNT" = "0" ]; then
            echo "ui-craft-detect: no diff-visible findings — skipping review comment post"
          else
            if ! gh api --method POST "repos/$REPO/pulls/$PR_NUMBER/reviews" --input "$REVIEW_FILE"; then
              echo "::warning::ui-craft-detect: failed to post inline review comments (see gh api output above) — this does not affect the scan's pass/fail result"
            fi
          fi`
    : "";

  return `name: ui-craft-detect

${GHA_CONFIG_MARKER} ${JSON.stringify(resolved)}
${GHA_VERSION_MARKER} ${VERSION}

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  # needed to post/update the sticky PR summary comment
  pull-requests: write${permissionsStatusLine}

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # --scope changed/files needs merge-base resolution against the
          # default branch — the default shallow (depth-1) checkout has no
          # history to resolve it, so --scope silently falls back to full
          # scan on every PR. Fetch full history so scoping actually works.
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Scan (pull_request — diff-scoped)
        if: github.event_name == 'pull_request'
        run: npx --yes ui-craft-detect@latest . --scope ${scope} --fail-on ${failOn}
      - name: Scan (push — full-repo, no PR diff context available)
        if: github.event_name != 'pull_request'
        env:
          SCAN_JSON_FILE: \${{ runner.temp }}/ui-craft-detect-scan.json
        run: |
          npx --yes ui-craft-detect@latest . --scope full --fail-on ${failOn} --json > "$SCAN_JSON_FILE"
          EXIT_CODE=$?
          cat "$SCAN_JSON_FILE"
          exit $EXIT_CODE${stickyCommentStep}${inlineCommentsStep}${commitStatusStep}
`;
}

/**
 * Locates and parses the `# ui-craft-detect-config:`/`# ui-craft-detect-version:`
 * marker comments in an already-generated workflow file's text. Pure function —
 * no filesystem access, no side effects. Used by `ci config`/`ci upgrade`
 * (read-modify-write) as the "read" and "modify" halves.
 *
 * @param {string} text - full text of an existing workflow file
 * @returns {{config: GhaConfig, version: string}}
 * @throws {Error} if either marker is missing, or the config marker's JSON
 *   fails to parse (a hand-edited/corrupted marker must never be silently
 *   accepted — see spec scenario "Marker parse failure does not silently
 *   corrupt the file").
 */
export function parseWorkflowConfig(text) {
  const configMatch = new RegExp(`^${escapeRegExp(GHA_CONFIG_MARKER)} (.*)$`, "m").exec(text);
  if (!configMatch) {
    throw new Error(
      `could not find "${GHA_CONFIG_MARKER}" marker — is this a ui-craft-detect-generated workflow?`,
    );
  }
  const versionMatch = new RegExp(`^${escapeRegExp(GHA_VERSION_MARKER)} (.*)$`, "m").exec(text);
  if (!versionMatch) {
    throw new Error(
      `could not find "${GHA_VERSION_MARKER}" marker — is this a ui-craft-detect-generated workflow?`,
    );
  }

  let config;
  try {
    config = JSON.parse(configMatch[1]);
  } catch (err) {
    throw new Error(
      `failed to parse ${GHA_CONFIG_MARKER} marker as JSON (${err.message}) — the marker may have been hand-edited into an invalid state; refusing to proceed`,
    );
  }

  return { config, version: versionMatch[1].trim() };
}

/** Escapes regex metacharacters in a literal string used inside `new RegExp(...)`. */
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Rewrites an already-generated workflow file's body, given an updated
 * config. This is a FULL regen (template-authoritative — see design's
 * resolved open question): the entire file text is replaced by
 * `renderGHAWorkflow(config)`. There is no partial/line-level patch — the
 * config marker's values are what "win" over template defaults on the next
 * render, not the surrounding YAML (which is always regenerated fresh from
 * the current template). This guarantees `ci config`/`ci upgrade` never
 * leave a workflow with a stale mix of old/new step bodies.
 *
 * @param {GhaConfig} config
 * @returns {string}
 */
export function replaceMarkers(config) {
  return renderGHAWorkflow(config);
}


function parseInitHookArgs(argv) {
  const flags = {
    husky: false,
    native: false,
    githubAction: false,
    all: false,
    dryRun: false,
    yes: false,
    help: false,
    unknown: [],
  };
  for (const a of argv) {
    if (a === "--husky") flags.husky = true;
    else if (a === "--native") flags.native = true;
    else if (a === "--github-action") flags.githubAction = true;
    else if (a === "--all") flags.all = true;
    else if (a === "--dry-run") flags.dryRun = true;
    else if (a === "--yes" || a === "-y") flags.yes = true;
    else if (a === "--help" || a === "-h") flags.help = true;
    else flags.unknown.push(a);
  }
  return flags;
}

function printInitHookHelp() {
  process.stdout.write(
    `ui-craft-detect init-hook \u2014 install pre-commit hooks or CI workflow\n\n` +
      `Usage:\n` +
      `  ui-craft-detect init-hook [options]\n\n` +
      `Modes:\n` +
      `  (no flag)        auto-detect: .husky/ exists \u2192 husky; else native\n` +
      `  --husky          write ${HOOK_HUSKY_PATH}\n` +
      `  --native         write ${HOOK_NATIVE_PATH} (+ chmod +x)\n` +
      `  --github-action  write ${HOOK_GHA_PATH}\n` +
      `  --all            write all three\n\n` +
      `Flags:\n` +
      `  --dry-run        print what would be written; write nothing\n` +
      `  --yes, -y        overwrite existing files without prompting\n` +
      `  --help, -h       this help\n`,
  );
}

export async function fileExists(p) {
  try {
    await fs.stat(p);
    return true;
  } catch {
    return false;
  }
}

function simpleDiff(before, after) {
  const a = before.split(/\r?\n/);
  const b = after.split(/\r?\n/);
  const out = [];
  const max = Math.max(a.length, b.length);
  for (let i = 0; i < max; i++) {
    if (a[i] === b[i]) continue;
    if (a[i] !== undefined) out.push(red(`- ${a[i]}`));
    if (b[i] !== undefined) out.push(c("32", `+ ${b[i]}`));
  }
  return out.join("\n");
}

function prompt(question) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

/**
 * Write `content` to `relPath` (relative to cwd), creating parent dirs.
 * If the file exists and differs, show a diff and confirm unless `yes`.
 * If `executable`, chmod +x.
 * Returns { written: boolean, reason?: string }.
 */
async function writeHookFile(cwd, relPath, content, { executable, yes, dryRun }) {
  const full = path.join(cwd, relPath);
  const parent = path.dirname(full);

  if (dryRun) {
    process.stdout.write(`\n${bold("--- " + relPath)}${executable ? dim(" (chmod +x)") : ""}\n`);
    process.stdout.write(content);
    if (!content.endsWith("\n")) process.stdout.write("\n");
    return { written: false, reason: "dry-run" };
  }

  const exists = await fileExists(full);
  if (exists) {
    const existing = await fs.readFile(full, "utf8");
    if (existing === content) {
      process.stdout.write(dim(`unchanged: ${relPath}\n`));
      return { written: false, reason: "unchanged" };
    }
    if (!yes) {
      process.stdout.write(`\n${bold(relPath)} already exists. Diff:\n`);
      process.stdout.write(simpleDiff(existing, content) + "\n");
      const answer = await prompt(`Overwrite ${relPath}? [y/N] `);
      if (!/^y(es)?$/i.test(answer.trim())) {
        process.stdout.write(dim(`skipped: ${relPath}\n`));
        return { written: false, reason: "declined" };
      }
    }
  }

  await fs.mkdir(parent, { recursive: true });
  await fs.writeFile(full, content, "utf8");
  if (executable) {
    try {
      fsSync.chmodSync(full, 0o755);
    } catch (err) {
      process.stderr.write(`warning: could not chmod +x ${relPath}: ${err.message}\n`);
    }
  }
  process.stdout.write(`${c("32", "wrote")} ${relPath}${executable ? dim(" (chmod +x)") : ""}\n`);
  return { written: true };
}

export async function runInitHook(argv) {
  const opts = parseInitHookArgs(argv);

  if (opts.help) {
    printInitHookHelp();
    process.exit(0);
  }

  if (opts.unknown.length > 0) {
    process.stderr.write(`error: unknown flag(s): ${opts.unknown.join(" ")}\n\n`);
    printInitHookHelp();
    process.exit(2);
  }

  const cwd = process.cwd();

  // Require a git repo (or a git init clearly recommended).
  const gitDirExists = await fileExists(path.join(cwd, ".git"));
  if (!gitDirExists) {
    process.stderr.write(`error: Not a git repository. Run \`git init\` first.\n`);
    process.exit(2);
  }

  // Decide which targets to write.
  let doHusky = opts.husky || opts.all;
  let doNative = opts.native || opts.all;
  let doGha = opts.githubAction || opts.all;

  if (!doHusky && !doNative && !doGha) {
    if (opts.dryRun) {
      // Dry-run with no mode flag: preview all three for discovery.
      doHusky = true;
      doNative = true;
      doGha = true;
      process.stdout.write(dim(`dry-run \u2014 previewing all three targets\n`));
    } else {
      // Auto-detect.
      const huskyDirExists = await fileExists(path.join(cwd, ".husky"));
      if (huskyDirExists) {
        doHusky = true;
        process.stdout.write(dim(`detected .husky/ \u2014 using husky mode\n`));
      } else {
        doNative = true;
        process.stdout.write(dim(`no .husky/ \u2014 using native mode\n`));
      }
    }
  }

  // Husky-specific warning when .husky/ is missing but --husky was forced.
  if (doHusky) {
    const huskyDirExists = await fileExists(path.join(cwd, ".husky"));
    if (!huskyDirExists) {
      process.stdout.write(
        yellow(
          `warning: .husky/ not found. If husky is not installed yet, run:\n` +
            `  npm install husky && npx husky init\n`,
        ),
      );
    }
  }

  const { dryRun, yes } = opts;

  if (doNative) {
    await writeHookFile(cwd, HOOK_NATIVE_PATH, NATIVE_HOOK_CONTENT, {
      executable: true,
      yes,
      dryRun,
    });
    if (!dryRun) {
      process.stdout.write(
        dim(`next: run \`git config core.hooksPath .githooks\` to activate.\n`),
      );
    }
  }

  if (doHusky) {
    await writeHookFile(cwd, HOOK_HUSKY_PATH, HUSKY_HOOK_CONTENT, {
      executable: true,
      yes,
      dryRun,
    });
    if (!dryRun) {
      process.stdout.write(
        dim(`next: ensure husky is installed (\`npm install husky && npx husky init\`).\n`),
      );
    }
  }

  if (doGha) {
    await writeHookFile(cwd, HOOK_GHA_PATH, renderGHAWorkflow(DEFAULT_GHA_CONFIG), {
      executable: false,
      yes,
      dryRun,
    });
    if (!dryRun) {
      process.stdout.write(
        dim(`next: commit ${HOOK_GHA_PATH} and push \u2014 the workflow runs on PRs to main.\n`),
      );
    }
  }

  process.exit(0);
}

// --- ci subcommands (Slice D) ----------------------------------------------
// `ci install` is a thin alias for `init-hook --github-action` (per design:
// aliasing, not renaming — `init-hook` keeps working, deprecated-but-supported).
// `ci config`/`ci upgrade` operate on an ALREADY-installed workflow file via
// the config/version marker scheme `renderGHAWorkflow` emits.

function printCiHelp() {
  process.stdout.write(
    `ui-craft-detect ci — manage the generated GitHub Actions workflow\n\n` +
      `Usage:\n` +
      `  ui-craft-detect ci install [options]   # write .github/workflows/ui-craft-detect.yml\n` +
      `  ui-craft-detect ci config [options]    # change settings on an already-installed workflow\n` +
      `  ui-craft-detect ci upgrade [options]   # regenerate the template body, preserving config\n\n` +
      `ci install options:\n` +
      `  --dry-run        show what would be written\n` +
      `  --yes, -y        overwrite without prompting\n\n` +
      `ci config options (read-modify-write on ${HOOK_GHA_PATH}):\n` +
      `  --scope full|files|changed\n` +
      `  --fail-on none|warning|error\n` +
      `  --comment true|false\n` +
      `  --inline-comments true|false\n` +
      `  --status true|false\n` +
      `  --dry-run        show what would be written; write nothing\n\n` +
      `ci upgrade options:\n` +
      `  --dry-run        show what would be written; write nothing\n\n` +
      `Global:\n` +
      `  --help, -h       this help\n`,
  );
}

/** Reads the installed workflow file's text, or exits 2 with a clear error. */
async function readInstalledWorkflowOrExit(cwd) {
  const full = path.join(cwd, HOOK_GHA_PATH);
  let text;
  try {
    text = await fs.readFile(full, "utf8");
  } catch (err) {
    process.stderr.write(
      `error: could not read ${HOOK_GHA_PATH} (${err.message}) — run \`ui-craft-detect ci install\` first\n`,
    );
    process.exit(2);
  }
  return text;
}

/** Parses a boolean CLI flag value ("true"/"false"), or exits 2 on garbage input. */
function parseBoolFlag(name, value) {
  if (value === "true") return true;
  if (value === "false") return false;
  process.stderr.write(`error: invalid value "${value}" for ${name}; expected true|false\n`);
  process.exit(2);
}

/**
 * Parses `ci config`'s flags into a partial config override object —
 * only keys the user actually passed are present, so unspecified settings
 * are left untouched when merged over the marker's current parsed config.
 */
function parseCiConfigArgs(argv) {
  const overrides = {};
  let dryRun = false;
  let help = false;
  const unknown = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--scope" || a.startsWith("--scope=")) {
      const value = a.startsWith("--scope=") ? a.slice("--scope=".length) : argv[++i];
      if (!SCOPE_VALUES.has(value)) {
        process.stderr.write(`error: invalid --scope value "${value}"; expected full|files|changed\n`);
        process.exit(2);
      }
      overrides.scope = value;
    } else if (a === "--fail-on" || a.startsWith("--fail-on=")) {
      const value = a.startsWith("--fail-on=") ? a.slice("--fail-on=".length) : argv[++i];
      if (!FAIL_ON_VALUES.has(value)) {
        process.stderr.write(`error: invalid --fail-on value "${value}"; expected none|warning|error\n`);
        process.exit(2);
      }
      overrides.failOn = value;
    } else if (a === "--comment" || a.startsWith("--comment=")) {
      const value = a.startsWith("--comment=") ? a.slice("--comment=".length) : argv[++i];
      overrides.comment = parseBoolFlag("--comment", value);
    } else if (a === "--inline-comments" || a.startsWith("--inline-comments=")) {
      const value = a.startsWith("--inline-comments=")
        ? a.slice("--inline-comments=".length)
        : argv[++i];
      overrides.inlineComments = parseBoolFlag("--inline-comments", value);
    } else if (a === "--status" || a.startsWith("--status=")) {
      const value = a.startsWith("--status=") ? a.slice("--status=".length) : argv[++i];
      overrides.status = parseBoolFlag("--status", value);
    } else if (a === "--dry-run") dryRun = true;
    else if (a === "--yes" || a === "-y") {
      // accepted for symmetry with install/upgrade; config never prompts.
    } else if (a === "--help" || a === "-h") help = true;
    else unknown.push(a);
  }
  return { overrides, dryRun, help, unknown };
}

async function runCiInstall(argv) {
  // Thin alias: `ci install` == `init-hook --github-action`.
  await runInitHook(["--github-action", ...argv]);
}

async function runCiConfig(argv) {
  const { overrides, dryRun, help, unknown } = parseCiConfigArgs(argv);

  if (help) {
    printCiHelp();
    process.exit(0);
  }
  if (unknown.length > 0) {
    process.stderr.write(`error: unknown flag(s): ${unknown.join(" ")}\n\n`);
    printCiHelp();
    process.exit(2);
  }
  if (Object.keys(overrides).length === 0) {
    process.stderr.write(
      `error: ci config requires at least one setting to change (--scope/--fail-on/--comment/--inline-comments/--status)\n\n`,
    );
    printCiHelp();
    process.exit(2);
  }

  const cwd = process.cwd();
  const text = await readInstalledWorkflowOrExit(cwd);

  let parsed;
  try {
    parsed = parseWorkflowConfig(text);
  } catch (err) {
    process.stderr.write(`error: ${err.message}\n`);
    process.exit(2);
  }

  // Marker's current values always win over template defaults; the
  // requested overrides win over the marker's current values.
  const nextConfig = { ...DEFAULT_GHA_CONFIG, ...parsed.config, ...overrides };
  const nextText = replaceMarkers(nextConfig);

  if (dryRun) {
    process.stdout.write(`\n${bold("--- " + HOOK_GHA_PATH)} (dry-run — not written)\n`);
    process.stdout.write(nextText);
    process.exit(0);
  }

  await fs.writeFile(path.join(cwd, HOOK_GHA_PATH), nextText, "utf8");
  process.stdout.write(`${c("32", "wrote")} ${HOOK_GHA_PATH}\n`);
  process.exit(0);
}

async function runCiUpgrade(argv) {
  const flags = { dryRun: false, help: false, unknown: [] };
  for (const a of argv) {
    if (a === "--dry-run") flags.dryRun = true;
    else if (a === "--help" || a === "-h") flags.help = true;
    else flags.unknown.push(a);
  }

  if (flags.help) {
    printCiHelp();
    process.exit(0);
  }
  if (flags.unknown.length > 0) {
    process.stderr.write(`error: unknown flag(s): ${flags.unknown.join(" ")}\n\n`);
    printCiHelp();
    process.exit(2);
  }

  const cwd = process.cwd();
  const text = await readInstalledWorkflowOrExit(cwd);

  let parsed;
  try {
    parsed = parseWorkflowConfig(text);
  } catch (err) {
    process.stderr.write(`error: ${err.message}\n`);
    process.exit(2);
  }

  if (parsed.version === VERSION) {
    process.stdout.write(`${HOOK_GHA_PATH} is already up to date (v${VERSION}).\n`);
    process.exit(0);
  }

  // Regenerate the template body from the CURRENT template, preserving the
  // marker's existing config values exactly (config marker wins over
  // template defaults — see design's resolved decision).
  const nextConfig = { ...DEFAULT_GHA_CONFIG, ...parsed.config };
  const nextText = replaceMarkers(nextConfig);

  if (flags.dryRun) {
    process.stdout.write(
      `\n${bold("--- " + HOOK_GHA_PATH)} (dry-run — v${parsed.version} → v${VERSION}, not written)\n`,
    );
    process.stdout.write(nextText);
    process.exit(0);
  }

  await fs.writeFile(path.join(cwd, HOOK_GHA_PATH), nextText, "utf8");
  process.stdout.write(
    `${c("32", "wrote")} ${HOOK_GHA_PATH} (v${parsed.version} → v${VERSION}, config preserved)\n`,
  );
  process.exit(0);
}

export async function runCi(argv) {
  const sub = argv[0];
  if (sub === "install") {
    await runCiInstall(argv.slice(1));
  } else if (sub === "config") {
    await runCiConfig(argv.slice(1));
  } else if (sub === "upgrade") {
    await runCiUpgrade(argv.slice(1));
  } else if (sub === "--help" || sub === "-h" || sub === undefined) {
    printCiHelp();
    process.exit(sub === undefined ? 2 : 0);
  } else {
    process.stderr.write(`error: unknown ci subcommand "${sub}"\n\n`);
    printCiHelp();
    process.exit(2);
  }
}

