// Package assets exposes the embedded harness asset trees, scaffold templates,
// and splash art that are bundled into the ui-craft binary at build time.
//
// Hand-authored harness asset tree:
//
//	Assets are committed directly under cli/assets/<harness>/skills/, commands/,
//	and agents/ subdirectories. For claude and opencode the commands/ dir holds
//	the ~23 lens command files. For cursor, codex, and gemini (no command
//	support) the lens dirs are kept as flat peer SKILL.md files under skills/.
//	There is no generate step and no runtime freshness guard — the embedded FS
//	is the canonical source of truth.
//
// Review agent definitions:
//
//	Agent definitions are committed directly under cli/assets/agents/<harness>/
//	(not generated by CI) because they originate from the canonical agents/
//	directory at the repo root. They are NOT automatically kept in sync — drift
//	between agents/ and cli/assets/agents/claude/ is caught by:
//	  make check-agent-copies   (developer gate)
//	  CI workflow on agents/** and cli/** changes (automated gate)
//	Two harness-specific subdirectories are embedded:
//	  agents/claude/  — Claude Code sub-agent format (name, description, tools, model, color)
//	  agents/opencode/ — OpenCode agent format (name, description only)
package assets

import (
	"embed"
	"io/fs"
)

//go:embed templates
var templatesFS embed.FS

//go:embed art
var artFS embed.FS

// agentsEmbedFS holds the review agent definition files. Unlike mirrors/, this
// directory is committed (not CI-generated) because agent definitions originate
// from the canonical agents/ directory at the repo root. Drift between
// agents/ and cli/assets/agents/claude/ is enforced by `make check-agent-copies`
// and the CI workflow. Two harness-specific subdirectories are included:
//
//   - agents/claude/  — Claude Code sub-agent format
//   - agents/opencode/ — OpenCode agent format
//
//go:embed agents
var agentsEmbedFS embed.FS

// harnessFS embeds the hand-authored per-harness asset tree. Each harness
// directory contains skills/, and (for claude/opencode) commands/ and agents/.
// This is the new source-of-truth layout that replaces mirrors/ for Slices 3+.
//
//go:embed claude opencode cursor codex gemini
var harnessFS embed.FS

// TemplateFS returns the embedded FS rooted at "templates/".
func TemplateFS() fs.FS {
	sub, err := fs.Sub(templatesFS, "templates")
	if err != nil {
		panic("assets: cannot sub templatesFS: " + err.Error())
	}
	return sub
}

// ArtFS returns the embedded FS rooted at "art/".
func ArtFS() fs.FS {
	sub, err := fs.Sub(artFS, "art")
	if err != nil {
		panic("assets: cannot sub artFS: " + err.Error())
	}
	return sub
}

// Agents returns the embedded sub-filesystem containing the review agent
// definitions for the named harness (e.g. "claude", "opencode"). The returned
// fs.FS is rooted at agents/<harness>/ so callers can walk it directly and write
// each .md file as a separate agent.
//
// Agent definitions are committed in cli/assets/agents/<harness>/ (not
// CI-generated) because they originate from the canonical agents/ directory at
// the repository root. They are always available in dev and CI builds — no sync
// step is required.
//
// Returns nil when:
//   - The harness does not support native sub-agents (Cursor, Codex, Gemini have
//     no subdirectory under agents/ and are therefore absent from agentsEmbedFS).
//   - The harness subtree is absent for any other reason (defensive guard).
//
// Callers (core.Plan AgentProvider) must treat nil as "skip gracefully".
func Agents(harnessName string) fs.FS {
	path := "agents/" + harnessName
	if _, err := fs.Stat(agentsEmbedFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(agentsEmbedFS, path)
	if err != nil {
		return nil
	}
	return sub
}

// SkillsFS returns the embedded sub-filesystem for the skills of the named
// harness (e.g. "claude", "cursor"). The returned fs.FS is rooted at
// <harness>/skills/ so callers can walk it and get depth-1 entries like
// "ui-craft/SKILL.md" directly (no extra harness prefix).
//
// Returns nil when the harness subtree does not exist.
func SkillsFS(harnessName string) fs.FS {
	path := harnessName + "/skills"
	if _, err := fs.Stat(harnessFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(harnessFS, path)
	if err != nil {
		return nil
	}
	return sub
}

// CommandsFS returns the embedded sub-filesystem for the slash commands of the
// named harness. The returned fs.FS is rooted at <harness>/commands/ and
// contains flat *.md files (one per command).
//
// Returns nil for harnesses that do not support commands (cursor, codex, gemini)
// or when the commands directory does not exist.
func CommandsFS(harnessName string) fs.FS {
	path := harnessName + "/commands"
	if _, err := fs.Stat(harnessFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(harnessFS, path)
	if err != nil {
		return nil
	}
	return sub
}

// HarnessAgentsFS returns the embedded sub-filesystem for the agent definitions
// under the new per-harness tree (cli/assets/<harness>/agents/). This is
// distinct from the legacy Agents() function which reads from cli/assets/agents/.
//
// Returns nil when the harness has no agents directory.
func HarnessAgentsFS(harnessName string) fs.FS {
	path := harnessName + "/agents"
	if _, err := fs.Stat(harnessFS, path); err != nil {
		return nil
	}
	sub, err := fs.Sub(harnessFS, path)
	if err != nil {
		return nil
	}
	return sub
}
